name: eslabon_flutter
description: Eslabón app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_app_check: ^0.4.0+1
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^3.0.0
  easy_localization: ^3.0.8
  go_router: ^16.2.0
  firebase_core: ^4.0.1
  firebase_auth: ^6.0.1
  firebase_messaging: ^16.0.1
  google_mobile_ads: ^6.0.0
  geolocator: ^14.0.2
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  webview_flutter: ^4.13.0
  url_launcher: ^6.3.2
  image_picker: ^1.2.0
  geocoding: ^4.0.0
  google_maps_flutter: ^2.12.3
  flutter_local_notifications: ^19.4.1
  font_awesome_flutter: ^10.9.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo_white.png
    - assets/icon.png
    - assets/icon.jpg
    - assets/eslabon_background.png
    - assets/selfie1.png
    - assets/selfie2.png
    - assets/selfie3.png
    - assets/selfie4.png
    - assets/default_avatar.png
    - assets/time.png
    - assets/countries.json
    - assets/provinces.json
    - assets/translations/