name: eslabon_flutter
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.1
  flutter_riverpod: ^2.5.1
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  intl: 0.20.2
  url_launcher: ^6.2.5
  image_picker: ^1.1.0
  firebase_storage: ^11.6.5
  go_router: ^14.1.4
  font_awesome_flutter: ^10.7.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.6.0
  video_player: ^2.8.1
  chewie: ^1.7.5
  firebase_messaging: ^14.7.2
  flutter_local_notifications: ^17.1.2
  cloud_functions: ^4.6.5
  provider: ^6.0.0
  http: ^1.2.0
  firebase_app_check: ^0.2.2+7
  google_mobile_ads: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/icon.png
    - assets/eslabon_background.png
    - assets/icon.jpg
    - assets/selfie1.png
    - assets/selfie2.png
    - assets/selfie3.png
    - assets/selfie4.png
    - assets/default_avatar.png
    - lib/data/countries.json
    - lib/data/provinces.json
    - assets/time.png
    - lib/translations/