// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1i60BmSVBxBI5eF5jgEOUaCILsw4ej0k',
    appId: '1:548781604480:web:8baa0998d17858dd96f065',
    messagingSenderId: '548781604480',
    projectId: 'eslabon-app',
    authDomain: 'eslabon-app.firebaseapp.com',
    storageBucket: 'eslabon-app.firebasestorage.app',
    measurementId: 'G-BGSF2KMY19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwkbo70gthTE7Dqr2Fyf8q9Dj3HhcxCR0',
    appId: '1:548781604480:android:91fd1f50679905ea96f065',
    messagingSenderId: '548781604480',
    projectId: 'eslabon-app',
    storageBucket: 'eslabon-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXye_Il9-zwA2NZMsDqrgGKnPozg23BPc',
    appId: '1:548781604480:ios:78254c64fed6494996f065',
    messagingSenderId: '548781604480',
    projectId: 'eslabon-app',
    storageBucket: 'eslabon-app.firebasestorage.app',
    iosBundleId: 'com.example.eslabonFlutter',
  );
}